Whitespace

diff --git a/examples/pydoop_submit/run_wordcount_minimal b/examples/pydoop_submit/run_wordcount_minimal
--- a/examples/pydoop_submit/run_wordcount_minimal
+++ b/examples/pydoop_submit/run_wordcount_minimal
@@ -19,12 +19,12 @@ PYTHONBIN=${PYTHONBIN:-python}
 
 
 if type -P hdfs >/dev/null; then
-	hdfs="$(type -P hdfs) dfs "
+  hdfs="$(type -P hdfs) dfs "
 elif type -P hadoop >/dev/null; then
-	hdfs="$(type -P hadoop) fs "
+  hdfs="$(type -P hadoop) fs "
 else
-	echo "Cannot find hdfs or hadoop executables" >&2
-	exit 1
+  echo "Cannot find hdfs or hadoop executables" >&2
+  exit 1
 fi
 
 zip -j ${MZIP} ../wordcount/new_api/${MPY}
@@ -37,10 +37,10 @@ ${hdfs} -put ${DATA} ${INPUT}
 ${SUBMIT_CMD} --python-zip ${MZIP} --python-program ${PYTHONBIN}\
               -D mapreduce.pipes.isjavarecordreader=true \
               -D mapreduce.pipes.isjavarecordwriter=true \
-							-D pydoop.hdfs.user=${USER} \
+              -D pydoop.hdfs.user=${USER} \
                --entry-point main \
               --log-level ${LOGLEVEL} --job-name ${JOBNAME} \
-              ${MODULE} ${INPUT} ${OUTPUT} 
+              ${MODULE} ${INPUT} ${OUTPUT}
 
 ${hdfs} -cat ${OUTPUT}/part'*' > ${RESULTS}
 
